### ISSUE TITLE
Show rebalancing alerts

### ISSUE THREAD

**Issue by rosik** [tarantool/vshard#290] opened 2021-08-05 16:34 UTC
Vshard storage info has useful field `alerts`, but it says almost nothing about the rebalancing process. Is it going well or is it stuck? The errors are logged but don't produce any alerts. What about saving the latest rebalancing error?

See also https://github.com/tarantool/cartridge/issues/1112, https://github.com/tarantool/cartridge/issues/941

**Comment by Gerold103** [comment] 2021-08-12 18:53
Duplicate of https://github.com/tarantool/vshard/issues/107.

**Closed** 2021-08-13 09:48 UTC
Labels: duplicate
